@TubeManager.API = http://localhost:5126

GET {{TubeManager.API}}
Accept: application/json

###
GET {{TubeManager.API}}/bookmarks

###
GET {{TubeManager.API}}/bookmarks/7aeb3894-44a7-4b20-8c86-39e89f2e0af6

###
POST {{TubeManager.API}}/bookmarks
Content-Type: application/json

{
  "Title": "Rozwiązujemy ZADANIA ALGORYTMICZNE na czas...",
  "VideoUrl": "https://www.youtube.com/watch?v=POY9A7sQT9Q",
  "ThumbnailUrl": "https://i.ytimg.com/vi/POY9A7sQT9Q/maxresdefault.jpg",
  "Channel": "DevMentors"
}

###
PUT {{TubeManager.API}}/bookmarks/7aeb3894-44a7-4b20-8c86-39e89f2e0af6
Content-Type: application/json

{
  "Title": "Rozwiązujemy ZADANIA",
  "VideoUrl": "https://www.youtube.com/watch?v=POY9A7sQT9Q",
  "ThumbnailUrl": "",
  "Channel": "DevMentors PL"
}

###
DELETE {{TubeManager.API}}/bookmarks/94eea9f9-0869-4029-abf9-475062f98a51
