@TubeManager.API = http://localhost:5126

###
GET {{TubeManager.API}}/bookmarks

//pagination
###
GET {{TubeManager.API}}/bookmarks?page=1&pageSize=20

###
GET {{TubeManager.API}}/bookmarks?page=1&pageSize=2

###
GET {{TubeManager.API}}/bookmarks?page=2&pageSize=2

###
GET {{TubeManager.API}}/bookmarks?page=1&pageSize=4

###
GET {{TubeManager.API}}/bookmarks/bb0e3a10-fe3b-4dea-a10c-efb5e007ab3f

###
POST {{TubeManager.API}}/bookmarks
Content-Type: application/json

{
  "Title": "Rozwiązujemy ZADANIA ALGORYTMICZNE na czas...",
  "VideoUrl": "https://www.youtube.com/watch?v=POY9A7sQT9Q",
  "ThumbnailUrl": "https://i.ytimg.com/vi/POY9A7sQT9Q/maxresdefault.jpg",
  "Channel": "DevMentors",
  "Description": "Dziś Flip i Flap programowania zmierzą się z testem... algorytmicznym (na szczęście podstawowym). Nie będą jednak działać razem, a zmierzą się w POJEDYNKU!"
}

###
PUT {{TubeManager.API}}/bookmarks/bb0e3a10-fe3b-4dea-a10c-efb5e007ab3f
Content-Type: application/json

{
  "Title": "Rozwiązujemy ZADANIA",
  "VideoUrl": "https://www.youtube.com/watch?v=POY9A7sQT9Q",
  "ThumbnailUrl": "",
  "Channel": "DevMentors PL"
}

###
DELETE {{TubeManager.API}}/bookmarks/dd732e7a-c7c3-42b2-8894-bae9168d8b0e

###
POST {{TubeManager.API}}/import

###
POST {{TubeManager.API}}/import
X-Custom-header1: abc1234
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="files"; filename="skytube-2024-03-05-075634.skytube"

< ../../../skytube-2024-03-05-075634.skytube
--WebAppBoundary--
