@TubeManager.API = http://localhost:5126

GET {{TubeManager.API}}
Accept: application/json

###
GET {{TubeManager.API}}/bookmarks

###
GET {{TubeManager.API}}/bookmarks/d9c72e5-bec4-4c3b-9bb9-5d03ff93c2db

###
POST {{TubeManager.API}}/bookmarks
Content-Type: application/json

{
  "videoTitle": "Rozwiązujemy ZADANIA ALGORYTMICZNE na czas...",
  "videoUrl": "https://www.youtube.com/watch?v=POY9A7sQT9Q",
  "thumbnailUrl": "https://i.ytimg.com/vi/POY9A7sQT9Q/maxresdefault.jpg",
  "channel": "DevMentors"
}

###
PUT {{TubeManager.API}}/bookmarks

###
DELETE {{TubeManager.API}}/bookmarks